config/routes.rb
Rails.application.routes.draw do

  resources :chefs, only: [:index, :show]
  resources :orders, only: [:create, :show, :index]
  devise_for :users
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  has_many :orders
  has_many :menus
  validates :name, presence: true
  has_attachment :avatar

  def short_description
    description[0..50] + "..."
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :chef
  validates :name, :description, :meal_type, :price_per_guest, presence: true
  has_attachments :photos, maximum: 3



  after_validation :upcase_meal_type

  def upcase_meal_type
    self.meal_type = meal_type.capitalize
  end

  def appetizer
    regexer[1]
  end

  def dessert
    regexer[3]
  end

  def main_dish
    regexer[2]
  end

  def regexer
    self.description.match(/Appe[\w]+?: (.+)\.?.*Main.*: ?([\w ]+).*Dessert: ([\w ]+)/)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :chef
  belongs_to :user
  belongs_to :menu
  validates :guests, :address, :event_type, :date, presence: true


  def total_price
    self.guests * self.menu.price_per_guest
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :store_current_location


  private

  def after_sign_in_path_for(resource)
    if session[:current_location]
       session[:current_location]
    else
      root_path
    end
  end

  def store_current_location
    if request.get? && !devise_controller?
       session[:current_location]=request.path
    end
  end
end

app/controllers/chefs_controller.rb
  class ChefsController < ApplicationController
  skip_before_action :authenticate_user!


  def index
    if params[:food_choice] == "Meal Type"
      @chefs = Chef.all
    else
      @chefs = Chef.joins(:menus).where(menus: {meal_type: params[:food_choice]}).distinct
    end
  end


  def create
    @chef = Chef.new(chef_params)
    @chef.save
    redirect_to root
  end

  def new
    @chef = Chef.new
  end

  def show
    @chef = Chef.find(params[:id])
    if params[:date].nil? || params[:date].empty?
      @date = Date.today
    else
      @date = Date.parse(params[:date].split("/").rotate(-1).join("/"))
    end
    # In the view — the menu that is selected
    if params[:menu_id]
      @selected_menu = Menu.find(params[:menu_id])
    elsif params[:food_choice] == "Meal Type" or params[:food_choice].nil?
      @selected_menu = @chef.menus.first
      # Iterate on those in the view to show other menus
    else
      @selected_menu = @chef.menus.select {|menu| menu.meal_type == params[:food_choice]}.first # dynamically change with params later!
    end
    @other_menus = @chef.menus.reject { |m| m.id == @selected_menu.id }
    @order = Order.new(chef:@chef, menu:@selected_menu)
  end




  private

  def chef_params
    params.require(:chef).permit(:name)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new
    @menu.save
  end

  def index
    @menus = Menu.all
  end

  def destroy
  end

  def update
  end

  def edit
  end

  def add
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def index
    @orders = current_user.orders
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.save
    if @order.save
      redirect_to order_path @order
    else
      redirect_to(:back, notice:"Order was not saved!")
    end
  end

  def update
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:address, :event_type, :guests, :date, :chef_id, :menu_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @chefs = Chef.first(3)
    # instance variiable that will hold an array of all UNIQUE meal_types found in Menus
    @meal_types = Menu.all.map { |m| m.meal_type }.uniq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chefs/_other_menus_card.html.erb
<div class="other-menus-card">
  <div class="owl-carousel-wrapper">
    <div class="owl-carousel">
      <% @selected_menu.photos.each do |photo| %>
      <div>
        <%= cl_image_tag  photo.path, height: 300, width: 400, crop: :fill %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="meal-type-blue-box">
   <p><%= @selected_menu.meal_type %></p>
  </div>
   <div class="meal-description-white-box">
   <p><%= @selected_menu.description %></p>
   </div>
 <div class="other-menus-card-blue-box">
   <div class="details-icon">
     <%= cl_image_tag("notebook_u0pfwb.png", :width=>50, :height=>50, :crop=>"fill") %>
     <p>Details</p>
   </div>
 </div>
</div>

app/views/chefs/backupshow.html.erb
  <div class="other-menucontainer">
  <h3 class="text-center">Other Menus:</h3>
  <% @other_menus.each do |menu| %>
    <div class="other-menus-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path menu.photos.second.path, height: 300, width: 400 , crop: :fill%>')">
     <div class="meal-type-blue-box">
      <p><%= menu.meal_type %></p>
     </div>
     <div class="meal-description-white-box">

      <p><%= menu.description %></p>

     </div>
      <div class="other-menus-card-blue-box">

       <div class="details-icon">
      <%= cl_image_tag("notebook_u0pfwb.png", :width=>50, :height=>50, :crop=>"fill") %>
      <p>Details</p>
      </div>
      </div>
  <% end %>
  </div>

app/views/chefs/create.html.erb
<h1>Chefs#create</h1>
<p>Find me in app/views/chefs/create.html.erb</p>

app/views/chefs/index.html.erb
<!-- Flipping Card Back  -->

<div class="index-css">
  <div class="container">
    <div class="row">
      <% @chefs.each do |chef| %>
      <div class="col-xs-12 col-sm-4">
        <div class="flip3D">
          <div class="new-chef-card back-chef-card">
            <div class="top-section-back title-font"><h5 class="text-index">Preview of <%= chef.name%>'s menus</h5></div>
            <% chef.menus.limit(2).each do |item| %>
            <div class="menu-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path item.photos.sample.path, height: 300, width: 400, crop: :fill%>')">
              <div> <%= item.name %></div>
              <%= link_to "", chef_path(id: chef.id, food_choice: params[:food_choice], date: params[:end_date]), class: "index-card-link" %>
            </div>
            <% end %>
            <div class="bottom-section-back text-center">
              <ul class="list-inline">
                <li><a href=""><i class="fa fa-instagram"></i></a></li>
                <li><a href=""><i class="fa fa-facebook"></i></a></li>
                <li><a href=""><i class="fa fa-twitter"></i></a></li>
              </ul>
            </div>
          </div>
          <!-- back end -->


          <!-- Flipping Card Front  -->
          <div class="new-chef-card front-chef-card">
            <div class="top-section-front" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path chef.menus.sample.photos.sample.path, height: 300, width: 400, crop: :fill %>')"></div>
            <div class="chef-avatar">
              <%= cl_image_tag chef.avatar.path, width: 100, height: 100, crop: :thumb, gravity: :face %>
            </div>
            <div class="bottom-section-front">
              <h5><%=  chef.name %></h5>
              <p><%=  chef.description[0..150] + "..." %></p>
            </div>
          </div>
        </div><!-- front end -->
      </div>
      <% end %>
    </div><!-- back end -->
  </div>
</div>
</div>

app/views/chefs/new.html.erb
<h1>Chefs#new</h1>
<p>Find me in app/views/chefs/new.html.erb</p>

app/views/chefs/show.html.erb
<!-- Selected Menu from Index Page | cards & carousel -->
<div class="container-menu">
   <h2 class="text-center">Book this menu:</h2>
  <div class="other-menus-card">
    <div class="owl-carousel-wrapper">
      <div class="owl-carousel">
        <% @selected_menu.photos.each do |photo| %>
        <div>
          <%= cl_image_tag  photo.path, height: 325, width: 400, crop: :fill %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="menu-price">
      <p><%= @selected_menu.price_per_guest %> DKK </p>
    </div>
    <div class="meal-type-blue-box text-center">
     <p><%= @selected_menu.meal_type %></p>
   </div>
   <div class="meal-description-white-box">
     <p>Appetizer: <%= @selected_menu.appetizer %></p>
     <p>Main Dish: <%= @selected_menu.main_dish %></p>
     <p>Dessert: <%= @selected_menu.dessert %></p>
   </div>
   <div class="other-menus-card-blue-box">
     <div class="details-icon">
       <%= cl_image_tag("notebook_u0pfwb.png", :width=>50, :height=>50, :crop=>"fill") %>
       <p>Details</p>
     </div>
   </div>
  </div>


  <!-- Booking Form | can only be viewed when logged in -->
 <div class="form_booking">
  <% if current_user %>
  <div class="form_new ">
    <%= simple_form_for(@order) do |f| %>
    <%= f.error_notification %>
    <div class="form_new_design">
      <div class="form-inputs">
        <%= f.input :address, required:false, :input_html => { :class => 'field' }%>
        <%= f.input :guests, required:false , :input_html => { :class => 'field', min: 0 }%>
        <%= f.input :date, selected: @date, required:false, :input_html => { :class => 'field' } %>
        <%= f.input :event_type, required:false, :input_html => { :class => 'field' } %>
        <%= f.hidden_field :chef_id %>
        <%= f.hidden_field :menu_id %>
      </div>
      <div class="form-actions">
        <%= f.button :submit %>
        </div>
        <% end %>
        <% else %>
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Chef Picture & Description -->
<div class="text-center">
  <div class="container">
    <div class="row">
      <div class="show-wrapper">
            <div id="box">
              <div class="show-bubble">
                <div>
                  <%= cl_image_tag @chef.avatar.path, width: 450, crop: :thumb, gravity: :face, class: "avatar-chef" %>
                </div>
                <div class="show-rectangle"><h2><%= @chef.name %></h2>
                </div>
                <div class="show-triangle-l">
                </div>
                <div class="show-info">
                  <p>
                    <%= @chef.description %>
                  </p>
                </div>
              </div>
            </div>

             <!-- Other Potential Menus | cards & carousel -->
              <div class="other-menucontainer">
                <h3 class="text-center">Other Menus:</h3>
                <% @other_menus.each do |menu| %>
                <%= link_to chef_path(@chef, menu_id: menu.id) do %>
                  <div class="other-menus-card">
                    <div class="owl-carousel-wrapper">
                      <div class="owl-carousel">
                        <% menu.photos.each do |photo| %>
                        <div>
                          <%= cl_image_tag  photo.path, height: 325, width: 400, crop: :fill %>
                        </div>
                        <% end %>
                      </div>
                    </div>

                  <div class="menu-price">
                    <p><%= menu.price_per_guest %> DKK </p>
                  </div>
                  <div class="meal-type-blue-box text-center">
                    <p><%= menu.meal_type %></p>
                  </div>
                  <div class="meal-description-white-box">
                    <p>Appetizer: <%= menu.appetizer %></p>
                    <p>Main Dish: <%= menu.main_dish %></p>
                    <p>Dessert: <%= menu.dessert %></p>
                  </div>
                  <div class="other-menus-card-blue-box">
                    <div class="details-icon">
                      <%= cl_image_tag("notebook_u0pfwb.png", :width=>50, :height=>50, :crop=>"fill") %>
                      <p>Details</p>
                    </div>
                  </div>
                  </div>
                <% end %>
                <% end %>
                </div>
          </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'http://res.cloudinary.com/dcy45rdne/image/upload/v1496319231/carrot_logo.png' %>
    <title>Green House - Book a vegan chef! </title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Crafty+Girls" rel="stylesheet">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:js) %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/menus/add.html.erb
<h1>Menus#add</h1>
<p>Find me in app/views/menus/add.html.erb</p>

app/views/menus/create.html.erb
<h1>Menus#create</h1>
<p>Find me in app/views/menus/create.html.erb</p>

app/views/menus/destroy.html.erb
<h1>Menus#destroy</h1>
<p>Find me in app/views/menus/destroy.html.erb</p>

app/views/menus/edit.html.erb
<h1>Menus#edit</h1>
<p>Find me in app/views/menus/edit.html.erb</p>

app/views/menus/index.html.erb
<h1>Menus#index</h1>
<p>Find me in app/views/menus/index.html.erb</p>

app/views/menus/new.html.erb
<h1>Menus#new</h1>
<p>Find me in app/views/menus/new.html.erb</p>

app/views/menus/update.html.erb
<h1>Menus#update</h1>
<p>Find me in app/views/menus/update.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
    <h3>All the chefs I have booked</h3>

<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<!-- Order Confirmation Header -->
<div class="confirmation-title">
  <h2><%= cl_image_tag("Greenconfirmation.png", :width=>80, :height=>80, :crop=>"fill") %>Your booking is confirmed!</h2>
  <h4> Below are your booking details </h4>
</div>


<!-- Chef Image -->
<div class="container container-size">
  <div class="row">
    <div class= "order-confirmation">
      <div class="col-xs-12 col-md-6">
        <div class="confirmation-chef show-bubble ">
          <div>
            <%= cl_image_tag @order.chef.avatar.path, width: 300,  crop: :thumb, gravity: :face, class: "avatar-chef" %>
          </div>
          <div class="show-rectangle">
            <h2><%= @order.chef.name %></h2>
          </div>
          <div class="show-triangle-l">
          </div>
        </div>
      </div>

      <!-- Order Details -->
      <div class="col-xs-12 col-md-6">
        <div class="confirmation-details">
          <h4> Booking Details </h4>
          <ul>
           <li class="border-confirmation">
            Number of guests:  <%= @order.guests %>
          </li>
          <li class="border-confirmation">
            Address:  <%= @order.address %>
          </li>
          <li class="border-confirmation">
            Date for the event:  <%= @order.date %>
          </li>
          <li class="border-confirmation">
            Type of event:  <%= @order.event_type %>
          </li>
          <li class="border-confirmation">
            Price: <%= @order.total_price %> DKK
          </li>
        </ul>
      </div>
    </div> <!-- Order Details Div Close  -->
  </div>
</div>
</div> <!-- Chef Image Div Close  -->

<!-- 3 Images for Selected Menu -->
<div class="menu-order-overview text-center">
  <h4>Your selected menu</h4>
  <ul class="list-inline">
    <% @order.menu.photos.each_with_index do |photo, index| %>
    <li>
      <div class="home-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.0)), url('<%= cl_image_path photo.path, height: 300, width: 400, crop: :fill %>')">
        <div class="confirmation-card-description">
          <% if index == 0 %>
          <h4 class="menu-course">Appetizer</h4>
          <% elsif index == 1 %>
          <h4 class="menu-course">Main Dish</h4>
          <% elsif index == 2 %>
          <h4 class="menu-course">Dessert</h4>
          <% end %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/pages/home.html.erb
<!-- Call To Action Instructions | Header -->

<div class="home-container">
  <h1> St<%= cl_image_tag("radish", width: 65, height: 65) %>p W<%= cl_image_tag("avocado", width: 65, height: 65) %>ndering </h1>
  <h2> around for <span class="greenText">VEGAN</span> food; </h2>
  <h3> find a chef! </h3>
</div>

<!-- Call To Action | Select Date & Select Type of Cuisine -->

<div class="home-search-wrapper">
  <form action="/chefs" method="get" class="form-inline home-form-box"">
    <div class="home-form-inputs">
        <%= select_tag 'food_choice', options_for_select(@meal_types.insert(0,"Meal Type")), {class: "form-control home-form-control"}  %>
      <input class="search datepicker form-control home-form-control" type="text" placeholder="When?" id= "select_date" name="end_date">
    </div>
    <div class="home-form-button">
      <button class="tbn-submit-btn btn btn-primary" type="submit">
        <span class="black-box-text">GET CHEF</span>
      </button>
    </div>
  </form>
</div>

<!-- New Back Ground < -->



<!-- How it works Cards -->

<h1 class="hiw-font text-center">How it works </h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="hiw-icons text-center"><%= cl_image_tag("search-icons", width: 80, height: 80) %>
          </div>
        <div class="design-card text-center"><p>Select preferred meal type and date you need chef over.</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="hiw-icons text-center"><%= cl_image_tag("menuicon", width: 80, height: 80) %>
        </div>

        <div class="design-card text-center"><p>Select chef and your preferred vegan menu.</p></div>

      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="hiw-icons text-center"><%= cl_image_tag("cheficon", width: 80, height: 80) %>
        </div>
        <div class="design-card text-center"><p>Specify eventy type and enjoy :).</p></div>
      </div>
    </div>
  </div>

  <!-- Chef Cards -->
  <div class="home-wrapper-card">
    <div class="container">
      <div class="row">
        <% @chefs.each do |chef| %>
        <div class="col-xs-12 col-sm-4">
          <div class="home-card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.2)), url('<%= cl_image_path chef.menus.sample.photos.sample.path, width: 200 %>');">
            <div class="home-card-description">
              <h2> <%= chef.name  %> </h2>
              <p>  <%= chef.short_description %> </p>
            </div>
            <%= cl_image_tag chef.avatar.path, width: 100, crop: :thumb, gravity: :face, class: "index-card-user avatar" %><a class="index-card-link" href="<%= chef_path(chef) %>" ></a>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id= "footer_all">
<div id="footer" style="transform: matrix(1, 0, 0, 1, 0, 100);">
  <ul class="list-inline">
    <li><a href=""><i class="fa fa-youtube"></i></a></li>
    <li><a href=""><i class="fa fa-instagram"></i></a></li>
    <li><a href=""><i class="fa fa-facebook"></i></a></li>
    <li><a href=""><i class="fa fa-twitter"></i></a></li>
  </ul>

  <div class="lemon_tree">
  <%= cl_image_tag("lemon_tree", width: 130, height: 130) %>
</div>

<div class="cherry_tree">
  <%= cl_image_tag("cherry_tree.png", width: 90, height: 90) %>
</div>

<div class="windmill">
  <%= cl_image_tag("windmill.png", width: 150, height: 150) %>
</div>

<div class="tractor">
  <%= cl_image_tag("tractor.png",width: 90, height: 90)
 %>
</div>
<div class="message">Made with <%= cl_image_tag("RealHeart_ek4hek.png", :height=>12, :width=>12, :crop=>"scale") %> in Copenhagen</div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon-fixed">
  <!-- Logo -->
  <div class="carrot_logo">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= cl_image_tag("carrot_logo.png") %>
    <p class="name">Green House</p>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- JP: Commenting Out since we do not require for Food  -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
    <div class="badge-container">
    </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://res.cloudinary.com/dcy45rdne/image/upload/c_scale,h_450,w_450/v1497005108/happy-dog_duyigb.jpg", class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <!--  <li>
            <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li> -->
          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <!-- JP: Commenting Out since we do not require for Food Project -->
   <!--  <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>